function final_valid_acc = TrainAndPrint(hyper_paras,nlen,d,K,trainX,trainx,trainy,trainY,...
                                        validationX,validationx,validationy,validationY,fileID,MX1s,...
                                        class_counts,class_starts)
    ConvNet = InitParas(hyper_paras.n1,hyper_paras.k1,hyper_paras.n2,hyper_paras.k2,nlen,d,K);
    plotTitle = strcat('n1=',string(hyper_paras.n1),',k1=',string(hyper_paras.k1),...
                       ',n2=',string(hyper_paras.n2),...
                       ',k2=',string(hyper_paras.k2),',eta=',string(hyper_paras.eta),...
                       ',rho=',string(hyper_paras.rho),',n batch=',string(hyper_paras.n_batch),...
                       ',n epochs=',string(hyper_paras.n_epochs));
    ConvNet = MiniBatchGD(trainX,trainy,validationX,validationy, hyper_paras,...
              ConvNet,nlen,d,K, plotTitle,0,MX1s,class_counts,class_starts,...
              trainx,trainY,validationx,validationY);
    final_valid_loss = ComputeLoss(validationx, validationY, ConvNet,nlen);
    final_valid_acc = ComputeAccuracy(validationx, validationy, ConvNet,nlen);
    if isnan(final_valid_loss)                
        final_valid_loss = 'inf';
    end
    result = strcat(plotTitle,' acc:' ,string(final_valid_acc),' loss:' ,string(final_valid_loss),'\n')
    fprintf(fileID,result);
end